# Generated by Django 2.1.4 on 2019-01-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentInfo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(db_column='userName', max_length=20)),
                ('userscore', models.CharField(db_column='userScore', max_length=20)),
                ('time', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'comment_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovieAwards',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('awardname', models.CharField(db_column='awardName', max_length=20, unique=True)),
                ('awardclass', models.CharField(db_column='awardClass', max_length=20)),
            ],
            options={
                'db_table': 'movie_awards',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('time', models.CharField(max_length=10)),
                ('director', models.CharField(max_length=20)),
                ('types', models.CharField(max_length=20)),
                ('releasedate', models.DateField(blank=True, db_column='releaseDate', null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('sumcomment', models.IntegerField(blank=True, db_column='sumComment', null=True)),
            ],
            options={
                'db_table': 'movie_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MoviePlay',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('moviesite', models.CharField(db_column='movieSite', max_length=10, unique=True)),
                ('movieurl', models.CharField(db_column='movieUrl', max_length=300)),
            ],
            options={
                'db_table': 'movie_play',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovieScore',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('fivestarrate', models.FloatField(blank=True, db_column='fiveStarRate', null=True)),
                ('fourstarrate', models.FloatField(blank=True, db_column='fourStarRate', null=True)),
                ('threestarrate', models.FloatField(blank=True, db_column='threeStarRate', null=True)),
                ('twostarrate', models.FloatField(blank=True, db_column='twoStarRate', null=True)),
                ('onestarrate', models.FloatField(blank=True, db_column='oneStarRate', null=True)),
            ],
            options={
                'db_table': 'movie_score',
                'managed': True,
            },
        ),
    ]
